local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "banner"
    label: "横幅设置"
    files:
      - name: "home_banner"
        label: "首页横幅"
        file: "content/banner.json"
        fields:
          - label: "幻灯片"
            name: "slides"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number"}
              - {label: "标题", name: "title", widget: "string"}
              - {label: "描述", name: "description", widget: "text"}
              - {label: "图片", name: "image", widget: "image"}
              - {label: "链接", name: "link", widget: "string"}
              - {label: "按钮文字", name: "buttonText", widget: "string"}

  - name: "home-settings"
    label: "首页设置"
    files:
      - name: "home_products"
        label: "首页产品展示"
        file: "content/home-products.json"
        fields:
          - label: "产品列表"
            name: "products"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number"}
              - {label: "标题", name: "title", widget: "string"}
              - {label: "描述", name: "description", widget: "text"}
              - {label: "图片", name: "image", widget: "image"}
              - {label: "链接", name: "link", widget: "string"}

  - name: "products"
    label: "产品"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Cotton-Swab-Machine", "Paper-Stick-Machine", "Extrusion-Machine", "Packaging-Machine"], default: "Cotton-Swab-Machine"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "blog"
    label: "博客"
    folder: "content/blog"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Company-News", "Industry-Updates", "Technical-Insights"], default: "Company-News"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}
